### ISSUE TITLE
[BUG] - pip and conda not installing?

### ISSUE THREAD

**Issue by alibama** [nebari-dev/nebari#1524]
### OS system and architecture in which you are running QHub

ubuntu 20.04

### Expected behavior

tested pip install and conda install - expected to get a working installation

### Actual behavior

nothin' worked

`Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - nebari`

### How to Reproduce the problem?

went through installing pip and terraform on a vanilla 20.04 system

### Command output

```bash session
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - nebari
```

**Comment by alibama** [comment]
just to be clear = working in digital ocean on a vanilla 20.04 ubuntu.... environment variables are set, and the terraform and python tools are updated

**Comment by iameskild** [comment]
Hi @alibama, thank you for giving Nebari a try! Last Thursday (Oct 27) we renamed the project from QHub to Nebari but have yet to cut an official first release. The plan is to do so this coming week. 

In the meantime you can either try installing QHub (`pip install qhub==0.4.5`) or try installing the last RC (`pip install nebari==2022.10.1rc2`). Otherwise, give us a few more days and you can install and deploy with the first official release of Nebari :)

**Comment by alibama** [comment]
Woohoo!  ran the release candidate = looking good!  if i weren't so excited about it i'd give ya another few days...  ;)
