### ISSUE TITLE
[ENH] - allow terraform plan and apply to run in separate stages

### ISSUE THREAD

**Issue by kalpanachinnappan** [nebari-dev/nebari#1538]
### Feature description

Separate `terraform plan` and `terraform apply` runs into 2 separate stages, so that they can be run independently of each other in CI (Gitlab CI for reference).

For example:
1. User makes change to `nebari-config.yaml`.
2. User commits and pushes changes to their branch, opens an MR.
3. The pipeline in the MR will run `terraform plan` and display the plan to the user.
4. User can choose to either make more changes based on the plan, or merge.
5. After merge, the pipeline runs `terraform apply` to actually apply the changes, and make the automated commit back to the repo.

**Suggestion**: Add a flag to `nebari deploy`, like `nebari deploy --plan`, or `nebari deploy --preview`, which would trigger only a `terraform plan`, and show the user which files are planned to be changed.

### Value and/or benefit

Being able to run `terraform plan` separately from `terraform apply` in `nebari deploy` would allow teams to preview changes before they are automatically committed back to the repo by CI. This allows the team to catch potential issues in the `.tf` files before they are automatically committed back to the repo by CI.

**Comment by iameskild** [comment]
Hi @kalpanachinnappan, thanks for the feature request. I can see something like being useful in certain situations. 

For some context, at the moment, the values in the `nebari-config.yaml` act as inputs for the Terraform scripts (01-08). Given that the scripts are broken down into stages, one stage often times also relies on the output values from the previous step. These output values may not be known until after the `terraform apply`. 

Piggy-backing off the workflow you outlined above, a possible solution might look something like:
- create a tfvars file for each stage 
  - if needed, this would include saving the output from the previous stage
  - this tfvars file would need to be updated during each deployment 
- add a `nebari deploy --plan` (or `--preview`) flag that will display the output of the `terraform plan` command
- add this new command to the `nebari-linter.yaml` so that users can see the planned changes as a comment on their PR/MR

In the meantime, you can try use `terraform plan` directly by just pointing to the stage you want to see the plan for and passing the appropriate input values:

```
cd stages/01-terraform-state/gcp
terraform plan
```
> If input variables are not provided, terraform should ask for them. 

> Note, `nebari` installs and uses a particular version of Terraform (currently version 1.0.5).

**Comment by dcmcand** [comment]
Currently this is not possible with Nebari's architecture. We are closing this issue now and will reexamine in the future if the architecture changes.
