### ISSUE TITLE
[BUG] - Pin dask-gateway, but not dask 

### ISSUE THREAD

**Issue by rsignell-usgs** [nebari-dev/nebari#2105]
### Describe the bug

Dask is pinned to a specific version in the `nebari-dask` metapackage, but doesn't need to be.   I've been using dask gateway pinned to 2022.10.0 as specified in the current metapackage, but unpinning dask and it's been fine.   There have been a lot of improvements to Dask over the last year that Nebari users are missing out on if they use `nebari-dask`:
```
$ conda activate nebari-git-dask
$ conda list dask
# packages in environment at /home/conda/nebari-git/envs/nebari-git-dask:
#
# Name                    Version                   Build  Channel
dask                      2022.11.1          pyhd8ed1ab_0    conda-forge
dask-core                 2022.11.1          pyhd8ed1ab_0    conda-forge
dask-gateway              2022.10.0          pyh8af1aa0_0    conda-forge
nebari-dask               2023.10.1            hd8ed1ab_0    conda-forge
```
Instead I've been using:
```
$ conda activate global-pangeo
$ conda list dask
# packages in environment at /home/conda/global/envs/global-pangeo:
#
# Name                    Version                   Build  Channel
dask                      2023.10.1          pyhd8ed1ab_0    conda-forge
dask-core                 2023.10.1          pyhd8ed1ab_0    conda-forge
dask-gateway              2022.10.0          pyh8af1aa0_0    conda-forge
```

### Expected behavior

see above

### OS and architecture in which you are running Nebari

aws

### How to Reproduce the problem?

see above

### Command output

```bash session
see above
```

### Versions and dependencies used.

nebari version v2023.10.1

### Compute environment

None

### Anything else?

see above

**Comment by dharhas** [comment]
@iameskild @dcmcand 

I'd like to target this work the 2023.11.1 release.

**Comment by iameskild** [comment]
I wonder if we can simply retire `nebari-dask` since at this point we only version we need to specify `dask-gateway`, and maybe not even that? 

I will upgrade `nebari-dask` to the latest version of `dask-gateway` but for the release after, perhaps we can consider just pinning the version of `dask-gateway` we want directly in the `dask-worker` base image: https://github.com/nebari-dev/nebari-docker-images/blob/main/dask-worker/environment.yaml

**Comment by iameskild** [comment]
https://github.com/conda-forge/nebari-dask-feedstock/pull/10

**Comment by dharhas** [comment]
@iameskild how do we communicate with the end user which version of dask gateway they need to include in their conda environment for a functional system (i.e. matching the deployed version). If we have a nebari-dask metapackage, that is one way of doing it but then we would need to use versions that matched nebari releases.

**Comment by iameskild** [comment]
@dharhas we can add it to our documentation and be explicit about it but I also think that recommending that folks use the corresponding `nebari-dask` version is a sensible solution. This hasn't really been an issue since we have not updated `dask-gateway` in awhile (most of the recent changes except for the last one were relatively minor).

**Comment by iameskild** [comment]
Closed by https://github.com/conda-forge/nebari-dask-feedstock/pull/10

**Comment by rsignell** [comment]
From the discussion at the community meeting, seems like we are leaning toward keeping the `nebari-dask` metapackage, but unpinning dask  from the `[recipe/meta.yml](https://github.com/conda-forge/nebari-dask-feedstock/blob/main/recipe/meta.yaml#L13-L15)` would be great.  Dask has distributed as a requirement so:
```
- dask
- dask-gateway==2023.9.0
```
should be sufficient
