### ISSUE TITLE
Test existing extensions with JLab 4

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#2134]

**Comment by kcpevey** [comment]
Pulling from the list [here](https://github.com/nebari-dev/nebari-docker-images/blob/ebc3c1f951b4ec2bccc94a93d1951c7f63958505/jupyterlab/environment.yaml#L24-L35)

| Extension | JLab 4 compat? | Min compat version | Comment |
| --------- | -------------- | ------------------ | ------- |
| [dask_labextension](https://github.com/dask/dask-labextension/pull/263) | Y | 7.0.0 |  |
| [jupyterlab-git](https://github.com/jupyterlab/jupyterlab-git/pull/1236) | Y | 0.50.0 |  |
| [sidecar](https://github.com/jupyter-widgets/jupyterlab-sidecar/pull/110) | Y | 0.7.0 |  |
| jupyter-videochat | N |  | No movement on the project since 4/22 |
| [ipywidgets](https://github.com/jupyter-widgets/ipywidgets/releases/tag/8.0.7) | Y | 8.0.7 |  |
| [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet/pull/1146) | Y | - | merged into main 11/23/23 |
| [pyviz_comms](https://github.com/holoviz/pyviz_comms/pull/114) | Y | 3.0.0 |  |
| [jupyter-resource-usage](https://github.com/jupyter-server/jupyter-resource-usage/releases/tag/v1.0.0) | Y | 1.0.0 |  |
| nbgitpuller | ? |  | Not exactly an extension? |
| [jupyterlab_code_formatter](https://github.com/ryantam626/jupyterlab_code_formatter/pull/300) | Y | 2.1.0 |  |
| [jupyterlab-spellchecker](https://github.com/jupyterlab-contrib/spellchecker/pull/128) | Y | 0.8.3 |  |

**Comment by kcpevey** [comment]
[Issue for deprecating the video chat ](https://github.com/nebari-dev/nebari/issues/2137)

**Comment by kcpevey** [comment]
[Issue for updating argo-jupyter-scheduler](https://github.com/nebari-dev/argo-jupyter-scheduler/issues/4)
[Issue for updating conda-store extension](https://github.com/conda-incubator/jupyterlab-conda-store/issues/29)
