### ISSUE TITLE
Upgrade path from Nebari 2023.1.1 to latest 2023.11.1

### ISSUE THREAD

**Issue by kalpanachinnappan** [nebari-dev/nebari#2145]
### Context

Our prod Nebari cluster is running on 2023.1.1, and we would like to upgrade it to the latest stable version, 2023.11.1.
What would be the safest upgrade path to take without data loss?

Thank you!

### Value and/or benefit

Upgrade minor versions without affecting the cluster data.

**Comment by rsignell** [comment]
We just recently went through this with the ESIP Nebari deployment on AWS, going from 2023.1.1 to 2023.10.1.    
* We backed up all the user data using the [Manual Backup Process](https://www.nebari.dev/docs/how-tos/manual-backup).
* We upgraded our nebari conda environment to the latest version.
* We ran `nebari upgrade -c nebari-config.yaml` multiple times, answering all the questions each time. 
* We restored all the user data.  
* We generated a CSV file of usernames from the user data folder and used that to regenerate user accounts for everyone using keycloak import (we use github auth so we just needed the usernames)
Not sure if there was a way to do this without losing the users.  @aktech ?

**Comment by dharhas** [comment]
Longer term, the approach I want to implement involves having a proper backup and restore. This is on the roadmap to build in January

- Backup everything in Nebari that has state
  - user folder data
  - keycloak data
  - conda-store data
  - anything else?
- deploy a clean install of the latest version of Nebari
- restore state from backups
- destroy previous nebari install

I think this will be a more robust solution than incremental update scripts, especially when jumping a large number of versions.

**Comment by rsignell** [comment]
@dharhas oh my, yes that would be an amazing improvement!

**Comment by marcelovilla** [comment]
Most likely you have already migrated upgraded your Nebari version. For posterity, I think @rsignell outlined a good approach for upgrading, taking into account the backup of existing data. This is specially necessary for AWS as [version 2023.7.1 triggered Terraform to replace the VPC](https://www.nebari.dev/docs/how-tos/configuring-keycloak#add-user-using-keycloak-admin-console) due to some changes on the AWS side of things.

As @dharhas mentioned, we're working on a backup and restore mechanism that will facilitate this process for users in the future. More information can be found on [this RFD](https://github.com/nebari-dev/governance/issues/49).

I'm closing this issue but feel free to reopen if necessary.
