### ISSUE TITLE
"Productionize" Nebari Self-Registration Capability

### ISSUE THREAD

**Issue by dharhas** [nebari-dev/nebari#2177]
### Context

We have been working on a self-registration capability in the following repo:

https://github.com/MetroStar/nebari-self-registration

This is a tracking issue to see if there are any extra steps we need to do before the 2024.1.1 release to make this usable.

potentially:

- move it to nebari org
- add keycloak realm overrides for email server 
- documentation
- anything else?

### Value and/or benefit

This is a POC that will allow us to setup coupon codes for folks to self register for access to a Nebari deployment.

**Comment by kcpevey** [comment]
I think the only blocker for the 2024.1.1 release here is [add keycloak realm overrides for email server](https://github.com/nebari-dev/nebari/issues/2180). 

Since we are still in very much an alpha state, I dont think it makes sense to document (advertise) this feature, yet. 

We have a repo in existence on the nebari-dev org for this work whenever we're ready to migrate. https://github.com/nebari-dev/nebari-registration

**Comment by kcpevey** [comment]
Migrating to nebari-dev will require us to "enable public GHCR images (if nebari isn't already doing that, or publish to quay.io via CICD) and publish there, and update the helm templates to look at nebari's GHCR by default."

**Comment by pavithraes** [comment]
This will be nice to have before **July 2024, i.e., around SciPy US 2024**

Next steps:
- Look into migrating to `nebari-dev` org?
- update theme to use Nebari themes

**Comment by Adam-D-Lewis** [comment]
This has been done many times at this point.  Closing.  Feel free to reopen if needed
