### ISSUE TITLE
[ENH] - Integrate conda-store 2024.1.1 release

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#2186]
### Feature description

This issue is to add the latest conda-store release (2024.1.1) to Nebari. There are significant changes in this conda-store release so it will need thorough testing. 

### Value and/or benefit

Updated conda-store.

**Comment by dcmcand** [comment]
Testing:
I was able to create and use an environment in my personal namespace as an admin user
I was able to create and use an environment in a shared namepace as an admin user
I was able to create and use an environment in my personal namespace as an non-admin user
I was not able to create an environment in a shared namepace as an non-admin user, but was able to use one from the shared namespace

Anything else that I should test? @kcpevey @dharhas ?

**Comment by dcmcand** [comment]
- I was able to create and use an environment in my personal namespace as an admin user
-  I was able to create and use an environment in a shared namepace as an admin user
-  I was able to create and use an environment in my personal namespace as an non-admin user
-  I was not able to create an environment in a shared namepace as an non-admin user, but was able to use one from the shared namespace
- I was able to cancel a build of an environment using the FastAPI ui since that functionality is not yet exposed in conda-store-ui (https://github.com/conda-incubator/conda-store-ui/issues/347)

Yet to do: test a complex environment

**Comment by dcmcand** [comment]
Thanks @kcpevey , testing it now

**Comment by dcmcand** [comment]
The large env built in 25 minutes on my local install of nebari. I think that this is tested. @kcpevey @dharhas anything else you think we need to look at?

**Comment by dharhas** [comment]
Only other thing will be testing the GPU build feature that is being developed in 

- https://github.com/conda-incubator/conda-store/pull/721
- https://github.com/conda-incubator/conda-store-ui/pull/354

When those are ready. If we think those will make it for this release.
