### ISSUE TITLE
[MAINT] - Local Integration Tests failing in CI

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#2205]
### Context

The Local Integration tests are failing on several PRs, example: https://github.com/nebari-dev/nebari/actions/runs/7507745462/job/20441910352?pr=2191

We'll need to investigate and fix this.

### Value and/or benefit

Stable CI ✨

**Comment by marcelovilla** [comment]
After fixing the Playwright tests, the [Deployment tests failed](https://github.com/nebari-dev/nebari/actions/runs/7757778648/job/21158022405). The issue stems from JupyterHub v4.x requiring the use of [XSRF tokens for cross-site checks](https://github.com/jupyterhub/jupyterhub/pull/4032). When trying to generate a JupyterHub API token, the session XSRF token (retrieved from the cookies) needs to be passed. This was [addressed](https://github.com/nebari-dev/nebari/pull/2232/commits/311b00d5cd9eedd62cb12e99fb73fa72c14721eb) but the issue still persisted for some of the tests because the API returns `{'status': 403, 'message': 'XSRF cookie does not match POST argument'}` when a server is already running. I did not found a solution for this but was able to make it work by making sure that the Playwright test stops the server once finished and by having the token creation be a session-scoped fixture (rather than a function-scoped one).

Finally, the [JupyterHub Notebook tests failed](https://github.com/nebari-dev/nebari/actions/runs/7789178337/job/21240195504). I am certain they are failing because of the same issue, but for these tests we are calling a CLI command from [`jhub-client`](https://github.com/Quansight/jhub-client) which does the same authentication and token retrieval logic behind the scenes. `jhub-client` has not been updated in the past two years and I am unsure on who is using it at this point. Before engaging in the maintenance of it, I suggest we remove the [JupyterHub Notebook tests](https://github.com/nebari-dev/nebari/blob/3c7c3157019eceeafc4518e3dd83e631718b2ee4/.github/workflows/test_local_integration.yaml#L170-L184) as they are testing the same functionality that is already being tested in the Playwright tests (i.e., running a notebook).
