### ISSUE TITLE
[BUG] - Cleanup step on takes way too long on CI (25 minutes!)

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/nebari#2252]
### Describe the bug

Local integration tests take 45 minutes. Given that local installation is challenging it is important that contributors have fast feedback loop on CI. This is mostly true because tests run fast, but oh boy 25 minutes for teardown (Cleanup nebari deployment)? Its over half of the time!

It seems that there must be a bug, I don't imagine it should take as much time. In fact, the logs have a couple of errors (apparently expected? I don't know). I suspect the cleanup is just running against timeouts.

![image](https://github.com/nebari-dev/nebari/assets/5832902/6a77ec60-3ce1-40e5-80ab-1a2cf190cbb6)

### Expected behavior

Terardown on CI takes about as long as setup

### OS and architecture in which you are running Nebari

GHA

### How to Reproduce the problem?

See for example latest commit on `main`: https://github.com/nebari-dev/nebari/actions/runs/7900785118/job/21563030088

### Command output

```bash session
Stage=stages/07-kubernetes-services failed to fully destroy
ERROR: not all nebari stages were destroyed properly. For cloud deployments of Nebari typically only stages 01 and 02 need to succeed to properly destroy everything
[terraform]:
```

### Compute environment

None

**Comment by viniciusdc** [comment]
Hi @krassowski, you are completely right, the main issue for the delayed destroy execution, is that usually, terraform relies on the response time from the Kubernetes API, which usually is stuck waiting for all resources related to a `staticset` or `deployment` to be removed -- I have also noticed this on other instances, and it seems to be "expected" in the sense of termination for all dependencies, but there are ways to countermeasure this at least on a test deployment scenario.

**Comment by viniciusdc** [comment]
> Stage=stages/07-kubernetes-services failed to fully destroy
ERROR: not all nebari stages were destroyed properly. For cloud deployments of Nebari typically only stages 01 and 02 need to succeed to properly destroy everything
[terraform]:

regarding this error, its being present since the previous introduction of the stages process, and originally it was related to terraform being unaware of some resources during its teardown process (the depency graphy is faulty). This is due to how we are deploying certain resources and loading then later (data), we are envisioning a better way to handle each stage which might address this problem, or at least grant more information

**Comment by marcelovilla** [comment]
@krassowski we are working on fixing this (and [CI feedback times in general](https://github.com/nebari-dev/nebari/issues/2413)). We think using `kind` directly to delete the local cluster instead of relying on terraform (via `nebari destroy`) might be a feasible solution.
