### ISSUE TITLE
[ENH] - Upgrade Grafana to latest

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2401]
### Feature description

We're using Grafana: v8.3.3 (30bb7a93ca) - https://github.com/grafana/grafana/releases/tag/v8.3.3

Latest Grafana: [10.4.2 (2024-04-10)](https://github.com/grafana/grafana/releases/tag/v10.4.2)

Upgrade to the Latest.

### Value and/or benefit

The current version is over 2 years old and the newer dashboard is much better and also has nicer and more intuitive UI for searching through Loki logs.

**Comment by viniciusdc** [comment]
I think the main dragging point on this would be compatibility; if bumping its version does not break anything, then, at least to me, this looks like a reasonable step forward. Whoever checks this out needs to make sure this Prometheus support is compliant, as it will probably be updated as well.

**Comment by kcpevey** [comment]
@marcelovilla any updates on this one?

**Comment by marcelovilla** [comment]
@kcpevey I'm working on it. I have some changes in https://github.com/nebari-dev/nebari/compare/develop...upgrade-grafana that work for new deployments. However, I'm running into two issues:

* Our current Dashboards have a deprecation warning in the latest Grafana version because of https://grafana.com/docs/grafana/latest/developers/angular_deprecation/. I need to figure out the implications of this.
* When upgrading the chart for existing deployments, I'm running into the following error:
```
Error: error validating "": error validating data: ValidationError(Alertmanager.spec): unknown field "automountServiceAccountToken" in com.coreos.monitoring.v1.Alertmanager.spec
```
