### ISSUE TITLE
[ENH] - Setup alerts for uptime monitoring

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2558]
### Feature description

After we have setup some sort of uptime monitoring: https://github.com/nebari-dev/nebari/issues/2557 it would be very useful to setup alerts on those like:
- Email
- Slack, etc

### Value and/or benefit

- Know immediately when the system's health is compromised

**Comment by kcpevey** [comment]
Things I think would be interesting to see:
* notification when things go down (might not be possible since we're monitoring from _within_, we might have to settle for some sort of heartbeat push update)
* heartbeat check on conda-store
* how long the current users have been on the platform (to identify when someone has accidentally left a server running)
* Current apps
  * number of apps running 
  * total number of servers used by these apps
  * uptime for each app
* Daily/weekly stats
  * total number of users per day
  * average uptime per user
  * total disk usage for user storage/shared directories
  * total disk usage by conda-store
  * max/average memory consumption of jhub server and conda-store server

Some of these will likely be outside scope for the initial POC. I imagine some of them may require storing data over time which is likely outside of scope as well. I couldn't tell which could be achieved by scraping Loki logs and which would require an additional bit of storing information so I've just thrown all the ideas out there.
